### ISSUE TITLE
Topicos Janeiro

### ISSUE THREAD

**Issue by plebhash** [plebemineira/bhbitdevs.org#1]

**Comment by narcelio** [comment]
BIP do OP_CAT

https://github.com/bitcoin/bips/blob/3d31e5c8947bf5d2d8ba02dc22c5302085b9f91b/bip-%3F%3F%3F-cat.mediawiki

**Comment by a-moreira** [comment]
ETFs aprovados: discussão sobre prós, contras e consequências 😅

**Comment by a-moreira** [comment]
quantum cats e shenanigans que os fazem funcionar
https://twitter.com/rot13maxi/status/1745983083608789345

**Comment by plebhash** [comment]
Layers 2 com EVM usando BTC pra gas:
- https://www.satoshivm.io/
- https://www.gobob.xyz/

**Comment by a-moreira** [comment]
Layer 2 com EVM
* https://botanixlabs.xyz/en/home

**Comment by diegokolling** [comment]
Mixers banidos do bitcointalk.org https://twitter.com/nikzh/status/1730971053227159766?s=12&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
PR do TXHASH escrita: https://x.com/robin_linus/status/1734177107163369500?s=48&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
> BIP do OP_CAT
> 
> https://github.com/bitcoin/bips/blob/3d31e5c8947bf5d2d8ba02dc22c5302085b9f91b/bip-%3F%3F%3F-cat.mediawiki

COm OP_CAT, transações instantâneas na Ark como na LN https://x.com/robin_linus/status/1721878419175247958?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Combinação de covenants tomando corpo, uma análise de um Dev da Blockstream com as possíveis combinações e funcionalidades:

https://covenants.info/

**Comment by diegokolling** [comment]
Pool inaugura templates: https://x.com/ocean_mining/status/1737745210191564958?s=20

**Comment by narcelio** [comment]
MuSig2 na libsecp256k1

https://github.com/bitcoin-core/secp256k1/pull/1479

**Comment by diegokolling** [comment]
LNHANCE https://x.com/reardencode/status/1744066572627632298?s=20

**Comment by diegokolling** [comment]
BINANA https://x.com/Dr_DAO_/status/1748382424986472622?s=20

**Comment by diegokolling** [comment]
OP_TX, uma evolução do TXHASH mas, dentro do v1 tapscript: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-May/020450.html
