### ISSUE TITLE
Tópicos Setembro

### ISSUE THREAD

**Issue by diegokolling** [plebemineira/bhbitdevs.org#10]
Veja o link para os outros Bitdevs, onde você pode pegar inspiração para os seus próprios tópicos sugeridos.

https://github.com/plebemineira/bhbitdevs.org/issues/8

**Comment by UnidosPeloTesouroDireto** [comment]
Com qual frequência um node repassa blocos ou transações inválidas? Li que são necessárias “algumas transações inválidas” para que um node exclua outro e coloque ele na "lista negra"? Essa "lista negra" é apenas daquele node ou é passada pra frente? Se eu atualizar meu node para 22 milhões de BTC, ele desconecta da rede na hora?

**Comment by zeroseis** [comment]
[The Key to FROST: What is Distributed Key Generation?](https://blog.blockstream.com/the-key-to-frost-what-is-distributed-key-generation/)

**Comment by zeroseis** [comment]
[RAMBO Attack Steals Sensitive Data from Air-gapped Systems](https://primal.net/e/note17ar26fhcete70mjsfjcqdd0rylmy7y699243ld70jqc24wnr05wsc48aud)

**Comment by tuliorn** [comment]
Evolução dos Miners de loteria
Bitaxe Gamma: https://x.com/altair_tech/status/1836419203080790024?t=ot7P3VJlhN9FQnpbRq5pEQ&s=19
BMM 101: https://shop.braiins.com/products/braiins-mini-miner-bmm-101-pre-order-12-2024

**Comment by tuliorn** [comment]
Fork da Samurai: https://x.com/econoalchemist/status/1837687516079489060?t=BABoP5jIriCVd33bFuP7jQ&s=19

**Comment by diegokolling** [comment]
O Bitcoin é uma armazenagem descentralizada? https://x.com/stevesimple/status/1837544142575927766?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
243 milhões de dólares pelo ralo… https://x.com/lopp/status/1836757720713547975?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Como é o anti-spam do Bitcoin e quais ataques do tipo já ocorreram? https://x.com/lopp/status/1835517907612090489?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
NOIST: a non-interactive, single-round t-of-n threshold signature scheme.

https://x.com/brqgoo/status/1835278458718462254?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Brick Wallet: a web frontend for NWC (Nostr Wallet Connect)

https://x.com/super_testnet/status/1834016108321669439?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
PPLNS-JD - a breakthrough in how to calculate the payouts based both on selected transactions and hash power provided.

@plebhash 

https://x.com/demand_pool/status/1833509389539676538?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Como calcular o tamanho mínimo das UTXOs

https://x.com/lopp/status/1833047373167067379?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
GAP limit pode te matar do coração:

https://x.com/lopp/status/1832981200048103787?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
O que acontece se a Coinbase for hackeada e perder absolutamente tudo?

https://x.com/francispouliot_/status/1832003127676977495?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
I'm proposing to stop the processing of unrequested transactions in Bitcoin
Core 22.0+ at TX message reception. An unrequested transaction is one
defined by which a "getdata" message for its specific identifier (either
txid or wtxid) has not been previously issued by the node [0].

This change is motivated by reducing the CPU DoS surface of Bitcoin Core
around mempool acceptance. Currently, an attacker can open multiple inbound
connections to a node and send expensive to validate, junk transactions.
Once the canonical INV/GETDATA sequence is enforced on the network, a
further protection would be to deprioritize bandwidth and validation
resources allocation, or even to wither connections with such DoSy peers. A
permissioned peer (PF_RELAY) will still be able to bypass such restrictions.

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-February/018391.html

**Comment by diegokolling** [comment]
Silent payments in the wild:

https://x.com/bitboxswiss/status/1831981915827757560?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Ark is pretty cool

https://x.com/peterktodd/status/1830552372075999691?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
56 mil nós de BTC

https://x.com/lopp/status/1838183115061080231?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by zeroseis** [comment]
[JoinStr: Decentralized CoinJoin Implementation Using Nostr](https://www.nobsbitcoin.com/joinstr-decentralized-coinjoin-implementation-using-nostr/)

**Comment by diegokolling** [comment]
Bip 300 e 301 atualizada 

https://x.com/truthcoin/status/1838538369464435055?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
[bitcoindev] Signing a Bitcoin Transaction with Lamport Signatures (no changes needed)

https://groups.google.com/d/msgid/bitcoindev/CAEM%3Dy%2BXyW8wNOekw13C5jDMzQ-dOJpQrBC%2BqR8-uDot25tM%3DXA%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by diegokolling** [comment]
https://x.com/nobsbitcoin/status/1838670063504613505?s=46&t=zAjxz5gV-hM4odRtK474uA

Bolt 12 merged!
