### ISSUE TITLE
Tópicos Outubro

### ISSUE THREAD

**Issue by diegokolling** [plebemineira/bhbitdevs.org#11]
Veja o link para os outros Bitdevs, onde você pode pegar inspiração para os seus próprios tópicos sugeridos.

https://github.com/plebemineira/bhbitdevs.org/issues/8

**Comment by UnidosPeloTesouroDireto** [comment]
Como funciona o mecanismo de força bruta de passphrase? 
Segundo esse site: 

https://www.security.org/how-secure-is-my-password/

É mais importante ser longo do que ser diferente.
A senha "aaaaaaaaaaaaaaaaaaaa" 20 vezes, é fácil de lembrar e mais difícil de quebrar do que "t%5B@zQ*w"

**Comment by elshitcoinermaximalista** [comment]
Sobre o BTC MAP como rodar localmente?

Como preencher as variáveis de ambiente corretamente?
https://github.com/teambtcmap/btcmap.org/blob/main/.env.example

**Comment by juancolchete** [comment]
Bitcoin e LORA

https://github.com/BTCtoolshed/MeshtasticBitcoinCore_Bridge

**Comment by narcelio** [comment]
Puzzle que o Jão Noctus resolveu

https://tabctb.com/six/thebeginning/thetree/grim/iacceptyourterms.html

**Comment by mateusnds** [comment]
https://groups.google.com/g/bitcoindev/c/Aee8xKuIC2s/m/cu6xej1mBQAJ?pli=1
https://github.com/bitcoin/bips/pull/1670

Rascunhos de BIPs sobre proteção quântica.

**Comment by devrenj** [comment]
Dicas para quem deseja migrar da web2 para web3, por que caminho seguir, quais tecnologias aderir, etc

**Comment by narcelio** [comment]
libbitcoin

https://delvingbitcoin.org/t/libbitcoin-for-core-people/1222

**Comment by narcelio** [comment]
História do cgminer

https://x.com/ckpooldev/status/1848949988178726993

**Comment by narcelio** [comment]
Floresta Wallet

https://floresta.flutterflow.app/

**Comment by diegokolling** [comment]
10 devs deixaram de poder ter tarefas "assigned" - o quie isso significa? Limpeza ou censura?

https://x.com/achow101/status/1847383175426953466

**Comment by diegokolling** [comment]
Spark, concorrente da Ark, da Lightspark - não, não é um trava-língua:

https://x.com/_arshbot/status/1849901462991585758?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Update da computação quantica @narcelio : https://arxiv.org/pdf/2410.08725

**Comment by diegokolling** [comment]
Consensus bug disclosed: https://x.com/darosior/status/1841846277262168149?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Ocean mining insults Sv2 community: https://x.com/thebluematt/status/1840778120611176757?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
BTCs de 16 anos são movidos: https://livecoins.com.br/carteiras-criadas-no-primeiro-mes-do-bitcoin-movem-250-btc-pela-primeira-vez/

**Comment by diegokolling** [comment]
AQUECIMENTO: Bitcoin Script Visualizer https://script.savingsatoshi.com/

**Comment by diegokolling** [comment]
AQUECIMENTO: 10101 winddown https://www.nobsbitcoin.com/10101-to-wind-down-operations-by-november-3rd/

**Comment by diegokolling** [comment]
Outro bug disclosed: https://bitcoincore.org/en/2024/09/18/disclose-headers-oom/

**Comment by diegokolling** [comment]
`ÀQUECIMENTO: 1 milhão de dólares para argumentar a favor ou contra opcat. https://groups.google.com/g/bitcoindev/c/awBtvpXKBcw

**Comment by diegokolling** [comment]
BTC Locked in L2: https://www.bitcoinlayers.org/?status=Charts&chart=separate&range=1y

**Comment by diegokolling** [comment]
Package relay to the rescue: https://mblack.io/posts/fixing-lightning-force-closures/
