### ISSUE TITLE
Tópicos de Novembro!

### ISSUE THREAD

**Issue by diegokolling** [plebemineira/bhbitdevs.org#12]
Deixe aqui os seus tópicos para o nosso último encontro do ano!

Inspiração: https://github.com/plebemineira/bhbitdevs.org/issues/8

**Comment by caduaguiar** [comment]
Gostaria de aprender mais sobre multisig bitcoin. 
E quais seriam as melhores formas de gerenciar mais de uma carteira Bitcoin

**Comment by caduaguiar** [comment]
1. Como você vê o impacto das soluções de segunda camada, como a Lightning Network, na escalabilidade do Bitcoin?

2. Quanto custa/necessário para criar um pool/channel  Lightning Network.
(necessário em termos de hardware) 

4. Vale a pena ter um No/channel Lightning Network.

**Comment by caduaguiar** [comment]
Existe algum desenvolvimento técnico ou proposta recente no Bitcoin Core que você acredita ser revolucionária para o protocolo?

**Comment by caduaguiar** [comment]
Quais os riscos de fazer DeFi com bitcoin?

**Comment by UnidosPeloTesouroDireto** [comment]
Se eu usar 12 palavras singlesig vou ter a xpub A.
Se eu usar as mesmas 12 palavras multisig, vou ter a xpub B.
Elas não são iguais.
A dúvida é:
A única mudança que gerou essa xpub diferente foi o caminho de derivação diferente ou há outras variáveis também?
O que é Script Semantics?

**Comment by atiradentes** [comment]
Em um hard fork, vender suas moedas na rede "perdedora" (bch, bsv...) não ajudaria a expor suas UTXOs também na rede correta?Não seria considerado uma reutilização do endereço?

**Comment by narcelio** [comment]
https://x.com/4moonsettler/status/1860658217983861233

**Comment by jaonoctus** [comment]
https://blog.dlsouza.lol/_site/bitcoin/testnet/2024/12/02/testnet4.html

**Comment by jaonoctus** [comment]
- Aquecimento: Como foi a Satsconf

**Comment by jaonoctus** [comment]
Aquecimento: [Product Director da Coinbase falando parar usuários não usarem VPN. CSO da Kraken discorda](https://x.com/c7five/status/1863783134732394908)

**Comment by narcelio** [comment]
https://pubky.org/

**Comment by narcelio** [comment]
> [O que está acontecendo na testnet4?](https://blog.dlsouza.lol/_site/bitcoin/testnet/2024/12/02/testnet4.html)

Deu 404. Consegui por este link: https://blog.dlsouza.lol/bitcoin/testnet/2024/12/02/testnet4.html

**Comment by jaonoctus** [comment]
@narcelio corrigi, Davidson tinha me passado o link errado

outra, faço uma continuação sobre o CTB6?

**Comment by diegokolling** [comment]
Como é o funding do Bitcoin Core? https://s3.amazonaws.com/1a1z.com/files/1A1z%20-%20Funding%20Bitcoin%20-%20Part%201.pdf

**Comment by diegokolling** [comment]
Bitcoin não custodial por e-mail, sem necessidade de se criar carteira: https://emailbtc.net/

**Comment by diegokolling** [comment]
Bitcoin Core 28: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-28.0.md

**Comment by diegokolling** [comment]
Bug resolvido: https://bitcoincore.org/en/2024/10/08/disclose-blocktxn-crash/

**Comment by diegokolling** [comment]
Stable de real usando Taproot Assets: https://bitcoinnews.com/press-release/joltz-eulen-stablecoin-on-lightning-depix/

**Comment by diegokolling** [comment]
Floresta 7: https://github.com/vinteumorg/Floresta/releases/tag/0.7.0

**Comment by Gabriel-Moya** [comment]
Fala galera, não sou de BH, rola uma transmissão pra eu conseguir participar também? :D

**Comment by diegokolling** [comment]
DLC devkit: https://bennyb.dev/blog/dlcdevkit

**Comment by diegokolling** [comment]
Aquecimento: Google mostra balanços na pesquisa.

https://www.google.com/search?q=bc1q9x95gufy4cze5w3ayaa3wkw648av4m59e7utphv92a4cqxtlrp6sezwapz

**Comment by diegokolling** [comment]
Avisos

Entrem no grupo do Whatsapp
Respeite a privacidade dos participantes.
Os meetups nunca são gravados.

Queremos todos a vontade para participar e discutir os assuntos programados, de forma anônima se assim o desejarem.

Agradecimentos

Agradecemos à Vinteum pela casa, comidas e bebidas, bem como a Livecoins pelos HH e a Vanq pelo espaço!

**Comment by narcelio** [comment]
> @narcelio corrigi, Davidson tinha me passado o link errado
> 
> outra, faço uma continuação sobre o [CTB6](https://github.com/plebemineira/bhbitdevs.org/issues/11#issuecomment-2445643976)?

Por mim só tinha este assunto! `:^D

**Comment by juancolchete** [comment]
Taproot X Segwit qual mais seguro?
