### ISSUE TITLE
Topicos Fevereiro

### ISSUE THREAD

**Issue by plebhash** [plebemineira/bhbitdevs.org#2]

**Comment by ReceitaMundial** [comment]
Oi, tenho uma questão que gostaria que fosse debatida no próximo bitdevs:

Eu achava que a passphrase era para dar mais segurança caso alguém encontrasse as 12 palavras anotadas, e na tentativa de KISS, nunca utilizei. Porém descobri que é para melhorar a entropia na geração das 12 palavras. Eu a electrum e criei as 12 palavras por lá sem passphrase. Já estou com mais de 200 utxos e não tenho nenhum interesse em consolidá-los (por privacidade). A maioria dos utxos tem KYC, tudo anotado na electrum.
Dessa forma pergunto:

1) Estou correndo risco?

2) O que pode ser feito para melhorar a segurança sem realizar 200 transações e nem enviar tudo para um novo endereço?

3) Não sei verificar PGP. Considerando a possibilidade de fazermos download da wallet com vírus (modificada) a única forma 100% segura (e simples, sem iancoleman por exemplo) de gerar as 12 palavras me parece ser a seguinte:
Gera as 12 palavras com passphrase em uma wallet, vai em outra wallet de outro fabricante e utiliza essa seed e verifica se geram as mesmas chaves privadas. Faz sentido?

4) A Sparrow também pode ser utilizada no tails? Como? Pelo que vi a Sparrow é para Windows, não é muito mais perigoso o risco de um vírus num Windows do que em um celular por exemplo? Não seria de alto risco utilizar uma carteira para pc? 

5) Também utilizo carteira de papel gerada no bitaddress. No youtube tem milhares de vídeos dizendo para não fazer isso, porém na prática nunca vi relato de problema com isso (a não ser os que deram bobeira na geração como entrar em site falso). Estou correndo risco real? 

6) Seria recomendável eu comprar uma HW? Qual?

Obrigado

**Comment by eipvi** [comment]
Analisei alguns tópicos que poderiam ser interessantes debatermos:

1.Implementação da rede Lightning nas empresas para fins de escalabilidade e usabilidade:
-Quais são as dificuldades que as empresas têm em aceitar a rede? Qual é a melhor forma de propor essa solução? Existem projetos que poderiam ser criados que ajudariam ainda mais a comunidade? Ela realmente ajudará na escalabilidade, ou podem existir outras concorrentes com soluções mais interessantes e seguras? O futuro da rede nos negócios…

2.Vantagens de desenvolver projetos que possam promover soluções de escalabilidade e as consequências de não promover esses projetos:
-As vantagens de desenvolver soluções para a comunidade que já está dentro e que ainda não conhece são evidentes. A falta desses projetos pode ter consequências quando realmente precisamos dessas soluções... Cada indivíduo desempenha um papel importante nessa jornada, pois em alguns anos vamos precisar de oferta e demanda de produtos e serviços para o uso do ativo e sobrevivência.

3.Futuro das carteiras de multiuso vs. as de BTC e Lightning:
-Os poupadores de BTC enfrentam riscos se escolherem carteiras inadequadas ao longo da jornada?É relevante considerar se as carteiras devem ser desenvolvidas separadamente para atender às necessidades específicas de cada rede?

4.Projetos que ainda não foram desenvolvidos mas podem ser criados com o Bitcoin, por onde começar?
-Existem várias possibilidades e oportunidades para sistemas que poderiam ser desenvolvidos. Então, o que ainda não foi criado e poderia beneficiar ainda mais a comunidade?!

**Comment by diegokolling** [comment]
Luke saindo da posição de enumerar BIPs, Roasbeef se candidatando.

**Comment by diegokolling** [comment]
AJTowns conversando privadamente sobre tópicos públicos do Core: experimento ou conspiração?

**Comment by diegokolling** [comment]
Por que você está aqui? Faz sentido ter alguma estratégia além do HODL, como talvez realizar um pouco em algum momento por "life profits"?

**Comment by diegokolling** [comment]
Libre Relay, com full RBF e unrestricted OP_RETURN: https://x.com/peterktodd/status/1732625293142077875?s=20

**Comment by diegokolling** [comment]
human-readable names to Bitcoin payment instructions  https://github.com/bitcoin/bips/pull/1551

**Comment by diegokolling** [comment]
Citrea: Sovereign Rollup + BitVM bridge https://x.com/citrea_xyz/status/1754883284893356368?s=20

**Comment by diegokolling** [comment]
Lightning Payouts https://twitter.com/BraiinsMining/status/1760319741560856983

**Comment by diegokolling** [comment]
Slipstream https://ir.mara.com/news-events/press-releases/detail/1343/marathon-digital-holdings-launches-slipstream

**Comment by diegokolling** [comment]
Terceirizando o pagamento de fees onchain: https://twitter.com/mononautical/status/1758262223456162279

**Comment by diegokolling** [comment]
120 páginas de emails privados de Satoshi: https://bitcoinmagazine.com/culture/newly-revealed-satoshi-email-correspondence-with-martti-malmi

**Comment by diegokolling** [comment]
basic vault with CAT https://delvingbitcoin.org/t/basic-vault-prototype-using-op-cat/576

**Comment by diegokolling** [comment]
Phoenix e Taproot https://acinq.co/blog/phoenix-swaproot
