### ISSUE TITLE
Topicos Março

### ISSUE THREAD

**Issue by plebhash** [plebemineira/bhbitdevs.org#3]

**Comment by tuliorn** [comment]
Bisq 2, mais uma forma de comprar Bitcoin. Uma grande melhoria da primeira versão
https://x.com/bisq_network/status/1769099858378457250?s=20

**Comment by narcelio** [comment]
Eu queria que o Bernardo explicasse o Stratum V2.

**Comment by lnunes** [comment]
Como funciona o DePix?
https://cointimes.com.br/depix-primeira-stablecoin-brasileira-na-liquid-network-entra-na-sideswap/

**Comment by tuliorn** [comment]
Ainda sobre Stratum V2.
https://x.com/StratumV2/status/1770937720476405845?s=20

**Comment by ReceitaMundial** [comment]
Oi, tenho uma questão que gostaria que fosse debatida no próximo bitdevs de forma anônima:

Eu achava que a passphrase era para dar mais segurança caso alguém encontrasse as 12 palavras anotadas, e na tentativa de KISS, nunca utilizei. Porém descobri que é para melhorar a entropia na geração das 12 palavras (e também para gerar mais de uma carteira com as mesmas palavras, mas vamos ignorar isso). Eu uso a electrum e criei as 12 palavras por lá sem passphrase. Já estou com mais de 200 utxos e não tenho nenhum interesse em consolidá-los (por privacidade). A maioria dos utxos tem KYC, tudo anotado na electrum.
Dessa forma pergunto:

    1) Estou correndo risco? Qual em específico? Em quanto esse risco é maior que uma HW?

    2) O que pode ser feito para melhorar a segurança sem realizar 200 transações e nem enviar tudo para novos endereços?

    3) Já vi que gerar palavras na electrum e testar no iancoleman não funciona pois utilizam sistemas diferentes. Porém se gerar palavras na iancoleman+passphrase e depois digitá-la na electrum (bip39) aí geram os mesmos endereços. 
Iancoleman é seguro? Como faz para gerar da forma mais segura possível? Não sei conferir PGP...

    4) A Sparrow também pode ser utilizada no tails? Como? Pelo que vi a Sparrow é para Windows, não é muito mais perigoso o risco de um vírus num Windows do que em um celular por exemplo? Não seria de alto risco utilizar uma carteira para windows? Salvando a Sparrow no armazenamento persistente do Tails ela fica funcionando normalmente por lá? Aí gero as palavras nela mesma, é uma boa?

    5) Também utilizo carteira de papel gerada no bitaddress offline. No youtube tem centenas de vídeos dizendo para não fazer isso, porém na prática nunca vi relato de problema com isso (a não ser os que entraram em site falso). Estou correndo risco real? Costumo colocar 100 reais e esperar 1 mês, se ninguém roubar, coloco o restante. Porém já tem anos que utilizo e nunca tive nenhum problema..

    6) Já estou familiarizado com Tails+Electrum, mesmo assim seria recomendável eu comprar uma HW? Todo youtuber é financiado por elas então fica difícil saber... Tails com electrum é tão bom, inclusive para imprimir paperwallet pois já é um sistema operacional, copia e cola no libreoffice e já conecta com cabo direto na impressora... Além de ser facílimo esconder um pendrive.


Obrigado

**Comment by lnunes** [comment]
Vulnerabilidade incorrigível em processadores da Apple permite que hackers roubem suas criptomoedas.

https://twitter.com/livecoinsbr/status/1771211882231157008

https://gofetch.fail/

**Comment by narcelio** [comment]
Great Consensus Cleanup Revival

https://delvingbitcoin.org/t/great-consensus-cleanup-revival/710

**Comment by narcelio** [comment]
> Oi, tenho uma questão que gostaria que fosse debatida no próximo bitdevs de forma anônima:

Ok, discutiremos!

**Comment by narcelio** [comment]
https://mempool.space/block/0000000000000000000341cc26cda4af82cd25f7063c448772228cbf2836915b?audit=false

**Comment by diegokolling** [comment]
VLS 0.11 https://gitlab.com/lightning-signer/validating-lightning-signer/-/releases/v0.11.0

**Comment by diegokolling** [comment]
Phoenixd https://www.nobsbitcoin.com/phoenixd-released/

**Comment by diegokolling** [comment]
Hedgehog https://twitter.com/super_testnet/status/1772647977892405739

**Comment by diegokolling** [comment]
Hong Kong is aiming to allow in-kind creations for spot [#Bitcoin](https://twitter.com/hashtag/Bitcoin?src=hashtag_click) ETFs, Bloomberg reports.  https://x.com/BitcoinMagazine/status/1772627283611664842?s=20

**Comment by diegokolling** [comment]
Knots no Umbrel 

https://x.com/leo_haf/status/1772550255650726347?s=20

**Comment by diegokolling** [comment]
Liana V5 RC e CASA Sucessão.

https://github.com/wizardsardine/liana

https://x.com/CasaHODL/status/1773002086843568268?s=20

**Comment by diegokolling** [comment]
Fedimint Mainnet:

https://x.com/fedibtc/status/1772678934242435392?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
Permissionless BitVM https://x.com/robin_linus/status/1772268261985386550?s=46&t=zAjxz5gV-hM4odRtK474uA

**Comment by diegokolling** [comment]
E-cash Bitcoin backed https://x.com/callebtc/status/1771098262910493161?s=46&t=zAjxz5gV-hM4odRtK474uA
