### ISSUE TITLE
Topicos Abril

### ISSUE THREAD

**Issue by plebhash** [plebemineira/bhbitdevs.org#4]

**Comment by UnidosPeloTesouroDireto** [comment]
Carteira multisig faz sentido para pessoa física? 
Ou só FALAR que é multisig já tem o mesmo efeito?

**Comment by a-moreira** [comment]
MEV in Bitcoin: https://bluematt.bitcoin.ninja/2024/04/16/stop-calling-it-mev/

**Comment by a-moreira** [comment]
ChainCode Labs BTC Scholarship: https://chaincode.applytojob.com/apply/F0HErM5FSk/Bitcoin-Scholarship

**Comment by a-moreira** [comment]
ZkCoins: https://gist.github.com/RobinLinus/d036511015caea5a28514259a1bab119

**Comment by a-moreira** [comment]
A Cashu based reward system for a pleb-friendly Bitcoin mining pool: https://github.com/plebemineira/plebpool/discussions/7

**Comment by a-moreira** [comment]
SHA256 implemented in Bitcoin Script: https://twitter.com/robin_linus/status/1780881121397428619

**Comment by a-moreira** [comment]
Discussion about new editors for the BIP process: https://groups.google.com/g/bitcoindev/c/cuMZ77KEQAA

**Comment by a-moreira** [comment]
Let's talk about Runes again (https://rodarmor.com/blog/runes/) since it's generating a lot of fees recently.

**Comment by vitorgitlima** [comment]
Embora o tema das runas ainda seja relativamente novo, é importante considerar seus potenciais impactos a médio e longo prazo, indo além das taxas elevadas, que nem sempre são negativas.

Portanto, gostaria de saber a opinião de vocês sobre os prós e contras dessa novidade e sua influência em diferentes aspectos. 

Quais seriam os impactos dessa nova 'coisa'
