### ISSUE TITLE
Topicos Maio

### ISSUE THREAD

**Issue by plebhash** [plebemineira/bhbitdevs.org#5]

**Comment by UnidosPeloTesouroDireto** [comment]
Uma transação com 1 confirmação há 30 minutos é mais segura que uma transação com 1 confirmação e 10 minutos?

**Comment by UnidosPeloTesouroDireto** [comment]
Na hora que liga o node, se não tem nenhum ponto centralizado, onde ele vai para se conectar com outros nodes ?
Como o bitcoin core escolhe com quais nodes vai se conectar?

**Comment by UnidosPeloTesouroDireto** [comment]
Uma chave privada singlesig te traz matematicamente ao endereço dela. 
Uma chave privada multisig também? As custódias colaborativas conseguem ver seu saldo?

**Comment by 20vigiar** [comment]
Quais as diferenças entre os endereços Bitcoin? quais as vantagens e desvantagens praticas de cada tipo de endereço?

**Comment by 20vigiar** [comment]
Quais as melhores praticas na hora de gerenciar uma carteira? qual o exemplo pratico de usar as "contas" dentro de uma carteira

**Comment by narcelio** [comment]
O Túlio vai explicar pra gente o funcionamento disto: https://x.com/JeremyRubin/status/1795430822180176245

**Comment by narcelio** [comment]
Compressed Transactions

https://github.com/bitcoin/bips/blob/master/bip-0337.mediawiki

**Comment by a-moreira** [comment]
Beta release of utreexod: https://mailing-list.bitcoindevs.xyz/bitcoindev/d5f47120-3397-4f56-93ca-dd310d845f3cn@googlegroups.com/T/#u

**Comment by a-moreira** [comment]
Release of Cashu.me – a Cashu wallet for the web: https://primal.net/e/note150ywd3rmpw086uwus22kyf45gvqk78r6dl8qm4rv65jem49hglts3um34a

**Comment by diegokolling** [comment]
BIP de Miniscript

https://groups.google.com/g/bitcoindev/c/wA-dW4t5BEY

**Comment by diegokolling** [comment]
Vou perguntar ao Narcélio a significância disso, atualização da libsecp2561:

https://groups.google.com/g/bitcoindev/c/zQfndwOTLOM

**Comment by diegokolling** [comment]
E-cash trazendo o BTC pra dark web de novo:

https://delvingbitcoin.org/t/dnm-ecash-and-privacy

**Comment by diegokolling** [comment]
Stable Channels:

https://delvingbitcoin.org/t/stable-channels-peer-to-peer-dollar-balances-on-lightning
