### ISSUE TITLE
Topicos Junho

### ISSUE THREAD

**Issue by plebhash** [plebemineira/bhbitdevs.org#6]

**Comment by UnidosPeloTesouroDireto** [comment]
Considerando que na rede liquid os saldos dos endereços são ocultos, como saber se os LBTC tem lastro?

**Comment by a-moreira** [comment]
Assange is free
https://x.com/wikileaks/status/1805390138945528183

**Comment by a-moreira** [comment]
LN + Nubank?
https://www.lightspark.com/news/nubank-announcement

**Comment by a-moreira** [comment]
Differential Fuzzing of Bitcoin implementations
https://delvingbitcoin.org/t/differential-fuzzing-of-bitcoin-implementations/208/6

**Comment by a-moreira** [comment]
Silent Payments inner workings:
https://medium.com/@ottosch/how-silent-payments-work-41bea907d6b0

**Comment by a-moreira** [comment]
I want to have an open discussion on self custody and Bitcoin adoption.
Inspired by this tweet by dpc (Fedimint co-creator): https://x.com/dpc_pw/status/1802917667327914464

**Comment by a-moreira** [comment]
A new BOLT12 website
https://bolt12.org/
https://primal.net/e/note1w6wh63r82chfz7g5rkzpfs9wh6z57qq2xa0llmsqxd606h9h4rcqffv2e4

**Comment by 20vigiar** [comment]
Qual a diferença entre um node econômico e um node onde conecto uma carteira nele? qual o risco em rodar um node econômico

**Comment by diegokolling** [comment]
Stable Channels: https://delvingbitcoin.org/t/stable-channels-peer-to-peer-dollar-balances-on-lightning

**Comment by diegokolling** [comment]
Narcelio: https://groups.google.com/g/bitcoindev/c/zQfndwOTLOM

**Comment by diegokolling** [comment]
Miniscript: https://groups.google.com/g/bitcoindev/c/wA-dW4t5BEY

**Comment by diegokolling** [comment]
Key Replacement: https://x.com/nunchuk_io/status/1805613264866525482

**Comment by diegokolling** [comment]
Mini Miner: https://shop.braiins.com/products/braiins-bmm-100-mini-miner-pre-order

**Comment by diegokolling** [comment]
BIP 352 Merged: https://github.com/bitcoin/bips/blob/master/bip-0352.mediawiki

**Comment by diegokolling** [comment]
DLC + Ecash: https://conduition.io/cryptography/ecash-dlc/
