### ISSUE TITLE
Topicos Julho

### ISSUE THREAD

**Issue by plebhash** [plebemineira/bhbitdevs.org#7]

**Comment by narcelio** [comment]
RFC 9591
The Flexible Round-Optimized Schnorr Threshold (FROST) Protocol for Two‑Round Schnorr Signatures

https://www.rfc-editor.org/rfc/rfc9591.html

**Comment by UnidosPeloTesouroDireto** [comment]
Qual é a fonte de tempo para o Bitcoin ajustar 10 minutos por bloco? Ele usa o relógio de quem?
Como a rede chega num consenso se vai ajustar +1,10% ou +1,11%?

**Comment by UnidosPeloTesouroDireto** [comment]
Catarina faz DCA de 100 reais por mês há 8 anos na coinext, que fica há 2 quarteirões do bitdevs. O funcionário da corretora tem todos os endereços de Catarina e percebe que ela já tem 96 UTXOs que já somam 0,5 BTC. O funcionário tem também KYC de Catarina. 
Catarina tem medo que um coinjoin possa sujar suas moedas limpas e então decide fazer uma transação fingindo gastar os BTCs. Qual o melhor número de entradas e saídas?

**Comment by narcelio** [comment]
Definitive explanation of my weird Bitcoin transaction

https://stacker.news/items/600187

**Comment by narcelio** [comment]
CUSF - “Core Untouched Soft Fork”

https://bip300cusf.com/cusf.pdf

**Comment by tuliorn** [comment]
Anuncio da Proton Wallet https://x.com/ProtonWallet/status/1816090220359475651

Bitcoin only https://x.com/ProtonWallet/status/1816108710386647344

**Comment by plebhash** [comment]
[Taproot Assets LN Channels](https://x.com/lightning/status/1815768786752164213)

**Comment by plebhash** [comment]
Empty Block report by 'mempool.space'

https://research.mempool.space/empty-block-report/

**Comment by plebhash** [comment]
visualizador Stratum V1

https://stratum.work/

**Comment by plebhash** [comment]
fedi launch

https://x.com/fedibtc/status/1820820426760880175

**Comment by mateusnds** [comment]
Solominer  BitAxe

https://livecoins.com.br/minerador-de-bitcoin-ganha-r-1-milhao-sozinho-usando-equipamento-caseiro/
