### ISSUE TITLE
Tópicos Agosto

### ISSUE THREAD

**Issue by diegokolling** [plebemineira/bhbitdevs.org#9]
Veja na outra issue aberta o link para os outros Bitdevs, onde você pode pegar inspiração para os seus próprios tópicos sugeridos.

https://github.com/plebemineira/bhbitdevs.org/issues/8

**Comment by UnidosPeloTesouroDireto** [comment]
Qual é a fonte de tempo para o Bitcoin ajustar 10 minutos por bloco? Ele usa o relógio de quem?
Como a rede chega num consenso se vai ajustar +1,11% ou +1,12%?

**Comment by diegokolling** [comment]
"Make Hidden Services Great Again" - https://devpost.com/software/el-tor?ref_content=my-projects-tab&ref_feature=my_projects

**Comment by diegokolling** [comment]
Segue seus Bitcoins com a YubiKey: https://blog.casa.io/secure-your-bitcoin-with-yubikey/?utm_source=twitter&utm_medium=social&utm_campaign=yubikey-launch&utm_term=bitcoin-2024&utm_content=nick-post

**Comment by diegokolling** [comment]
Um novo ataque: Dark Skippy e porque ele foi demonstrado numa Seedsigner: https://x.com/utxoclub/status/1820520960476561825

**Comment by diegokolling** [comment]
the new disclosure policy the Bitcoin Core will adopt for most reported vulnerabilities. : https://groups.google.com/g/bitcoindev/c/Q2ZGit2wF7w?pli=1

**Comment by diegokolling** [comment]
O Dream Team dos forks: https://x.com/roasbeef/status/1813658193631023416

**Comment by diegokolling** [comment]
Full RBF by default: por que é bom? https://petertodd.org/2023/why-you-should-run-mempoolfullrbf

**Comment by diegokolling** [comment]
1 bilhão de canais na LN por ano: https://x.com/peterktodd/status/1813928457946153056

**Comment by diegokolling** [comment]
Taproot Assets chegaram na LN: https://x.com/lightning/status/1815768786752164213

**Comment by diegokolling** [comment]
Last Mile solutions pra LN: https://bitcoinmagazine.com/technical/assessing-the-lightning-networks-last-mile-solutions

**Comment by diegokolling** [comment]
Ark sem covenants! https://x.com/ArkLabsHQ/status/1825542684553203722

**Comment by diegokolling** [comment]
Verificar computação arbitrária no BTC e uma ponte para sidechains: BitVM 2: https://x.com/alexeiZamyatin/status/1824034904516051335

**Comment by diegokolling** [comment]
Criptografia à prova decomputadores quânticos está ficando pronta: https://www.nist.gov/news-events/news/2024/08/nist-releases-first-3-finalized-post-quantum-encryption-standards

**Comment by diegokolling** [comment]
Proton Wallet Launch: https://www.nist.gov/news-events/news/2024/08/nist-releases-first-3-finalized-post-quantum-encryption-standards

**Comment by diegokolling** [comment]
Uma BitAxe encontrou um bloco: https://x.com/bitentrepreneur/status/1816173826754929125

**Comment by diegokolling** [comment]
MS Cloudstrike global outage: https://www.nytimes.com/2024/07/19/business/microsoft-outage-cause-azure-crowdstrike.html

**Comment by diegokolling** [comment]
Fedi Launch: https://www.fedi.xyz/blog/fedi-launches-world-s-first-community-superapp

**Comment by diegokolling** [comment]
University of Wyoming launch Bitcopin Research Institute: https://bitcoinmagazine.com/business/university-of-wyoming-launches-first-bitcoin-research-institute

**Comment by diegokolling** [comment]
Nova versão do Floresta: https://x.com/Vinteum_org/status/1825971821390557274
